### ISSUE TITLE
Possible invalid expression in BasicGetRecordsTests.presentSubjectProperty()

### ISSUE THREAD

**Issue by pandzel** [opengeospatial/ets-cat30#13]
The test is: "count(csw:SummaryRecord[dc:subject]) = ./@numberOfRecordsReturned".
However, considering that it might be more than one dc:subject in the record, shouldn't it rather be:
 "count(csw:SummaryRecord[dc:subject]) >= ./@numberOfRecordsReturned" ?

**Comment by rjmartell** [comment]
The expression looks ok. It counts the number of SummaryRecord elements that contain _at least one_ dc:subject child element. So the assertion will fail only if there is a record without dc:subject.

Now, dc:subject is an optional property. If no value exists is an _empty_ dc:subject element to be expected in the response? If not, then the test will have to select dc:title instead (which is a required element).
