### ISSUE TITLE
Unrecognized "Parameter" OpenSearch extension.

### ISSUE THREAD

**Issue by pandzel** [opengeospatial/ets-cat30#15]
According to the OpenSearch "Parameter" extension, it is possible to provide additional information for any Url element in the following manner:

&lt;Url xmlns:parameters="http://a9.com/-/spec/opensearch/extensions/parameters/1.0/"
&nbsp;type="text/html"
&nbsp;template="http://example.com/search"
&nbsp;parameters:method="POST"
&nbsp;parameters:enctype="application/x-www-form-urlencoded"&gt;
&nbsp;&nbsp;&nbsp;&lt;parameters:Parameter name="q" value="{searchTerms}"/&gt;
&nbsp;&nbsp;&nbsp;&lt;parameters:Parameter name="count" value="{itemsPerPage}" minimum="0"/&gt;
&nbsp;&nbsp;&nbsp;&lt;parameters:Parameter name="start" value="{startIndex}" minimum="0"/&gt;
&lt;/Url&gt;

Such structure causes schema validation to fail.

**Comment by rjmartell** [comment]
The RELAX grammar does allow foreign attributes to occur in os:Url. The schema was modified to also allow foreign elements in this context.
