### ISSUE TITLE
Multi-byte characters are not encoded

### ISSUE THREAD

**Issue by pandzel** [opengeospatial/ets-cat30#17]
Both BasicSearchTests.singleTermTextSearch() and OpenSearchCoreTests.singleKeywordSearch() are failing when the search term is a string with multi-byte characters, like: 소셜 미디어(사용 중지됨).

My recommendation would be to use URIUtils.getPercentEncodedString() to encode search term just like in each multipleKeywordSearch(), so:

BasicSearchTests.java:361
qryParams.put(CAT3.Q, URIUtils.getPercentEncodedString(keyword));

OpenSearchCoreTests.java:175
values.put(SEARCH_TERMS_PARAM, URIUtils.getPercentEncodedString(searchTerm));

**Comment by rjmartell** [comment]
The `searchTerms` param value must be URL-encoded according to the [latest OpenSearch spec](http://www.opensearch.org/Specifications/OpenSearch/1.1#The_.22searchTerms.22_parameter).

**Comment by rjmartell** [comment]
Fixed for next release (0.10).
