### ISSUE TITLE
Unexpected number of fail verdicts. expected:<2> but was:<1>

### ISSUE THREAD

**Issue by IanAWP** [opengeospatial/ets-cat30#19]
When building the test suite the VerifyTestNGController test suite is **expecting** two errors yet only encounters one, causing an error. I believe this is because the default test props file does not reference a geopackage.  As it is this does mean it's impossible to cleanly build from source without modification.

More to the point, though, when testing real geopackages I see that there are indeed two errors, every time.  If that is the expected case, then why are these tests written to fail? The fact that they fail by design mean that it is difficult to incorporate these tests into build workflow. Do these test need to be ignored?

The fact that the test package itself passes only when there are two test failures would normally indicate that the tests should be rewritten to be positive tests which pass when the expected behaviour. is encountered. There are lots of ways to fail a test, including ways that are not expected by the test suite.

If there is a good reason to keep the tests around even though they fail, that would also be useful information.  Thanks for producing the test suite at all, though!

**Comment by dstenger** [comment]
@IanAWP 

I cannot reproduce this error and all unit tests are passed successfully (including VerifyTestNGController).

Can you please check if you have still problems with the build?

You are mentioning GeoPackage in your comment. However, this is the CAT 3.0 test suite. Maybe, you opened this issue in the wrong repository?

**Comment by lgoltz** [comment]
@IanAWP What is the status of the ticket? I don't see why geopackages should be tested with the cat30 test suite. Was the issue created in the correct tracker?

**Comment by IanAWP** [comment]
Yes, almost definitely. In any case I don't have access to the tests we were running at that time, anymore, so I can't check. I will close this issue.
