### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/ets-cat30#24]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by dstenger** [comment]
Branch: https://github.com/lat-lon/ets-cat30/tree/defineBasicConformanceClasses-24

Fixed with commit: https://github.com/lat-lon/ets-cat30/commit/b7dedb2a33f4cb8d81ff6ffad5ecff5527fd6d15

**Comment by dstenger** [comment]
Pull request was created: #26
