### ISSUE TITLE
HTML report is not created with TEAM Engine 5.0 when using Web Browser Interface

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat30#27]
Instead, behaviour as described in https://github.com/opengeospatial/teamengine/issues/251 can be observed.

Can be reproduced on http://cite.opengeospatial.org/te2/.

Probably related to https://github.com/opengeospatial/ets-gpkg12/issues/17.

**Comment by keshav-nangare** [comment]
Fixed with this commit: 15bb995472e4a747256a0076c9ec37730f098fa4 .
