### ISSUE TITLE
clarify requirement 004

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-cat30#29]
cc @Schpidi 

As per http://docs.opengeospatial.org/is/12-176r7/12-176r7.html, Requirement 004 states:

> If a CSW request includes a parameter (e.g. outputFormat) that performs a function that is similar to an HTTP message header (e.g. Accept) and both are included in a request then their values must agree otherwise an InvalidParameterValue exception shall be raised as specified in Subclause 6.7.

In pycsw, we do a strict comparison of the HTTP Accept header and `outputFormat`, so the below works:

> curl "http://demo.pycsw.org/cite/csw?mode=opensearch&service=CSW&version=3.0.0&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q=&bbox=-23.17822265625,6.62353515625,49.90283203125,71.44287109375&time=2006-08-15T00:00:00.000Z/2006-08-22T23:59:59.000Z&outputformat=application/atom+xml&&startposition=1&maxrecords=500" --header "Accept: application/atom+xml"

However, if the user specifies `Accept: */*`, like:

> curl "http://demo.pycsw.org/cite/csw?mode=opensearch&service=CSW&version=3.0.0&request=GetRecords&elementsetname=full&typenames=csw:Record&resulttype=results&q=&bbox=-23.17822265625,6.62353515625,49.90283203125,71.44287109375&time=2006-08-15T00:00:00.000Z/2006-08-22T23:59:59.000Z&outputformat=application/atom+xml&&startposition=1&maxrecords=500" --header "Accept: \*/\*"

Then pycsw will complain because it not an exact match.

Should Accept: \*/\* and outputformat=application/atom+xml, for example, constitute passing Requirement 004?

**Comment by dstenger** [comment]
This is a tricky question as ```*/*``` includes ```application/atom+xml```. Thus, it could be argued that the more specific parameter is evaluated. On the other hand, the specification states that both parameters must agree. We should clarify the definition of ```agree``` here.

Can you point out the test which is connected to this requirement?

**Comment by tomkralidis** [comment]
@dstenger thanks for the info.  I can't find exactly where this is tested in ets-cat30, sorry.

**Comment by dstenger** [comment]
@tomkralidis 
You should also ask the CAT 3.0 SWG for further help/thoughts.
Do you need assistance for that?

**Comment by tomkralidis** [comment]
cc'ing @pvretano here for any clarification. Peter: should does `application/atom+xml` == `*/*` per above? Or does "values must agree" mean an exact literal match?

**Comment by ghobona** [comment]
My interpretation is that "values must agree" means an exact literal match. I will close this Issue on 2023-07-07, if there is no further clarification.

**Comment by pvretano** [comment]
Apologies, I missed this back in 2019!  Yes,  "application/atom+xml" does indeed equal "*/*" as does "application/xml".  Equating media types is usually never a literal string match.
