### ISSUE TITLE
Requirements: 093 add namespaceBindings

### ISSUE THREAD

**Issue by mbarbet** [opengeospatial/ets-cat30#30]
In BasicGetRecordsTests.java, in function presentTitleProperty() for resolve Xpath expression
```
ETSAssert.assertXPath(
                "not(csw:SummaryRecord[dc:type or subject or dc:format or ows:BoundingBox])",
                results, null);
```
I need to pass a Map with namespaceBinding 
```
Map<String, String> namespaceBindings = new HashMap<>();
namespaceBindings.put(Namespaces.DCMES,"dc");
namespaceBindings.put(Namespaces.CSW,"csw");
namespaceBindings.put(Namespaces.OWS,"ows");

ETSAssert.assertXPath(
                "not(csw:SummaryRecord[dc:type or subject or dc:format or ows:BoundingBox])",
                results, namespaceBindings);
```
I wonder if the problem come from my xml response or if we can enhance the test with this hashmap ?

Thanks

**Comment by dstenger** [comment]
Can you provide your response which is failing the test?

In general, the namespace bindings should be resolved in the document itself.

**Comment by dstenger** [comment]
So, validation of this response fails with the current version of the test but passes when namespaceBindings are passed to the assert?

**Comment by mbarbet** [comment]
Yes this is it.

**Comment by lgoltz** [comment]
The default namespace bindings are added in `ETSAssert.assertXPath()`:
https://github.com/opengeospatial/ets-cat30/blob/25c49757bd440985b63ff458fb71d8185524047e/src/main/java/org/opengis/cite/cat30/ETSAssert.java#L95-L98

The default namespaces are:
https://github.com/opengeospatial/ets-cat30/blob/25c49757bd440985b63ff458fb71d8185524047e/src/main/java/org/opengis/cite/cat30/util/NamespaceBindings.java#L94-L104

As far as I see the default bindings are the same as added in https://github.com/opengeospatial/ets-cat30/issues/30#issue-315540443. So it should not be necessary to pass the bindings in  `ETSAssert.assertXPath()`.

@mbarbet Which version of the test suite was used for testing? Did you test on [prod](http://cite.opengeospatial.org/teamengine/) or [beta](http://cite.opengeospatial.org/te2/) or a local environment? Can you provide the service URL for testing?

**Comment by mbarbet** [comment]
I used the master branch on a local environment. The service is not yet in production. I agree with your analysis, I do not understand what's going on. I forked the test project  so that all my project integration tests passed.

**Comment by lgoltz** [comment]
I've added a test using the response provided in https://github.com/opengeospatial/ets-cat30/issues/30#issuecomment-382732371 (commit https://github.com/opengeospatial/ets-cat30/commit/d70af188e2715d0c024b4f9782fcd0be73072adc). The test does not fail, so the response is valid according the xpath used for testing.

**Comment by mbarbet** [comment]
Thanks a lot for the job, i don't understand what append with my service, i will try later to fix it.

**Comment by lgoltz** [comment]
@mbarbet Does the failure still occur?

**Comment by lgoltz** [comment]
@mbarbet Please reopen this issue if the failure still occurs.
