### ISSUE TITLE
Create SoapUI tests and integrate them into Maven and Jenkinsfile

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat30#32]
See https://github.com/opengeospatial/ets-wms13/issues/56 for instructions.

Please use following service implementation: http://demo.pycsw.org/cite/csw?service=CSW&version=3.0.0&request=GetCapabilities

**Comment by keshav-nangare** [comment]
Fixed with this PR: #33.

**Comment by dstenger** [comment]
Successfully tested with `mvn clean com.smartbear.soapui:soapui-maven-plugin:test`.
