### ISSUE TITLE
Introduce Dockerfile and Maven Docker plugin

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat30#34]
Please see: [How to create Docker Images of test suites](https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites)

**Comment by keshav-nangare** [comment]
Changes are here: https://github.com/opengeospatial/ets-cat30/tree/feature-issue%2334

**Comment by dstenger** [comment]
@keshav-nangare 
Thank you for your work.
However, there was an update of https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites.
Can you please adjust the Maven configuration according to the updated manual?

**Comment by keshav-nangare** [comment]
@dstenger 

Updated the maven docker configuration.
