### ISSUE TITLE
Maven dependencies could not be resolved

### ISSUE THREAD

**Issue by PissedCapslock** [opengeospatial/ets-cat30#35]
Running `mvn install` on a new machine results in

````
[ERROR] Failed to execute goal on project ets-cat30: Could not resolve dependencies for project org.opengis.cite:ets-cat30:jar:1.3-SNAPSHOT: The following artifacts could not be resolved: org.geotoolkit.pending:geotk-xml-gml:jar:3.21, org.geotoolkit.pending:geotk-jtswrapper:jar:3.21, org.geotoolkit:geotk-epsg:jar:3.21: Failure to find org.geotoolkit.pending:geotk-xml-gml:jar:3.21 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
````

Looking at the rest of the log, it shows the following 3 warnings:

````
[WARNING] The POM for org.geotoolkit.pending:geotk-xml-gml:jar:3.21 is missing, no dependency information available
[WARNING] The POM for org.geotoolkit.pending:geotk-jtswrapper:jar:3.21 is missing, no dependency information available
[WARNING] The POM for org.geotoolkit:geotk-epsg:jar:3.21 is missing, no dependency information available
````

Only way I found to fix this was copy all those files from the maven cache of another machine, and adding them on the new machine.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

@keshav-nangare Can you please check if the dependencies are stored in Central Maven Repository [1]? If this is not the case, can you please search for a Maven repository storing such dependencies. This repository must be added to Maven Pom then.

[1] https://search.maven.org/

**Comment by keshav-nangare** [comment]
@dstenger 

I have tried to reproduce this issue on local machine bu deleting the `/.m2/repository` but build succeeded. Also tried on another machine Ubuntu and Mac os as well, still the build is successful and not able reproduce this issue.


There is no direct dependency in the ets-cat30 pom but ets has the `geomatics-geotk` which required all above dependency.
If we see the `geomatics-geotk` pom it has all above dependencies and `geotoolkit` 3.21 version is not in the central repository so the geomatics-geotk has added repository URL explicitly. 

https://github.com/opengeospatial/geomatics-geotk/blob/3e400ec87a46ab947221840a19ad5b1320598539/pom.xml#L323-L331

I will add this repository to ets-cat30 pom.

**Comment by keshav-nangare** [comment]
@dstenger 

I have added a repository to pom which has the geotoolkit dependency with the version 3.21. This can fix this issue.

**Comment by lgoltz** [comment]
@PissedCapslock Can you check if you build the current master and close this issue if it works?

**Comment by PissedCapslock** [comment]
Indeed, works now.
Thanks !
