### ISSUE TITLE
Update tests to use TEAM Engine 5.4

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat30#41]
Applies to integration and system tests.

SoapUI project must be updated as version was removed from URI to test suites of REST API (also see https://github.com/opengeospatial/teamengine/issues/261).
Please also update Maven configuration and set version of SoapUI Maven Plugin to 5.5.0.

See updated documentation: https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

Example, how this was solved for TEAM Engine tests: https://github.com/opengeospatial/teamengine/issues/400

**Comment by keshav-nangare** [comment]
Fixed with this commit: c0755201df037e1d8f1920cce3464e68374f8fae

**Comment by dstenger** [comment]
After fixing integration tests, build with `mvn clean install site -Pintegration-tests` is successful.
