### ISSUE TITLE
intermediate files filling up /tmp

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-cat30#5]
cc @rjmartell 

When running:

```bash
 java -jar target/ets-cat30-0.8-SNAPSHOT-aio.jar mycsw-props.xml
```
The `/tmp` directory gets populated with files like `entity-*.tmp` and `records-*.xml`.

Not sure if this is happening in this test suite or teamengine overall.  Or whether these are reused within the process or they are some leftover debugging.  If they are intentional, it would be useful to allow for a setting/argument to clean up these files (or not) before the process completes.

**Comment by rjmartell** [comment]
The `records-*.xml` file contains the sample records (GetRecordsResponse) retrieved from the service under test just before the test run starts. And the resource referenced by the iut param (capabilities doc) is also saved as `entity-*.tmp`). These can both be removed when the test run completes.

Perhaps they can be left alone at a certain logging level? For example, at CONFIG or lower.

**Comment by tomkralidis** [comment]
Is there a setting / flag which cleans these up (in lieu of the user)?

**Comment by rjmartell** [comment]
The temp files will be deleted when the test run is completed unless the test suite logger is enabled at the CONFIG level or lower. So, to keep them (presumably for diagnostic purposes) add the following line to the JDK logging config file:

```org.opengis.cite.cat30.level = CONFIG```

__Note__: The default config file is at `$JAVA_HOME/jre/lib/logging.properties`, but an application-specific one may be used by setting the system property `java.util.logging.config.file` (e.g. set the command line option -Djava.util.logging.config.file=$HOME/ets-logging.properties).
