### ISSUE TITLE
getResourceById() fails when working with UUID

### ISSUE THREAD

**Issue by pandzel** [opengeospatial/ets-cat30#6]
OpenSearchGeoTests.getResourceById() substitutes **{geo:uid}** parameter in the URL template with the actual uid. If that uid has a form of **UUID** starting and ending with curly braces, then an exception is thrown from within OpenSearchTemplateUtils.buildRequestURI() at the line:

return URI.create(template);

with the message logged into the report like this:

<![CDATA[Illegal character in query at index 63: http://*host*:*port*/*context*?uuid={413982A1-1E93-4317-B2FB-8CDCA555807C}&f=atom]]>

I would suggest to URLEncode an identifier before passing to the template.

**Comment by rjmartell** [comment]
You mean that the actual record _identifier_ (substitution value) contains curly braces? That seems a bit odd, but the specs don't appear to prohibit this.

New unit test to verify: [VerifyOpenSearchTemplateUtils#buildRequestURIWithIllegalChars](src/main/java/org/opengis/cite/cat30/util/OpenSearchTemplateUtils.java)
