### ISSUE TITLE
Looping through the list of Urls in OpenSearchDescription (RSS response)

### ISSUE THREAD

**Issue by pandzel** [opengeospatial/ets-cat30#7]
Several tests from OpenSearchCoreTests iterate through the list of Urls from the OpenSearchDescription, pick all which have a type ending with "xml" and use it to obtain list of record elements. This works fine for CSW response or Atom response with record elements marked accordingly as 'Record' or 'entry'. However, any Url of type "application/rss+xml" will fail because RSS returns items not records nor entries.

Example of such is executeExampleQueries(), which logs message like this:

"Expected one or more {http://www.opengis.net/cat/csw/3.0}Record elements in search results. expected [true] but found [false]"

It comes with the request like this:

Method: GET
Target URI: http://*host*:*port*/*context*?searchText=land&start=1&max=&bbox=&f=georss
Headers: {Accept=[application/rss+xml]}

**Comment by rjmartell** [comment]
Ah, the suite overlooks the RSS response which is not mentioned in the CSW3 spec and only the Atom response type is required in OpenSearch-Geo. But it would be easy to accommodate as GeoRSS-Simple is already supported in Atom feeds.
