### ISSUE TITLE
unlimited

### ISSUE THREAD

**Issue by mhogeweg** [opengeospatial/ets-cat30#8]
the maxRecords parameter has numeric values or 'unlimited'. what's the purpose of 'unlimited'. it raises some concerns when considering catalogs that have 100,000s or millions of items. denial of service attack waiting to happen.

for data listings as required by Data.gov, a common practice is to 'cache' this list on a daily basis server-side, that Data.gov can fetch. These lists are easily 100s of MB sized files without even containing the full metadata.

we suggest the test (the spec even) should not include this 'unlimited' option.

**Comment by tomkralidis** [comment]
fwiw in pycsw we have an (optional) server side config that sets a limit if desired which trumps even maxrecords=unlimited (and hence advertised in Capabilities). Agree that it is a potentially dangerous parameter value.

**Comment by mhogeweg** [comment]
yes, we also limit the max returned records. obviously that could be set to very large in order to pass the test. however, how does the test even know if it indeed received all records? therefor vote to remove this test.

**Comment by rjmartell** [comment]
Please submit a spec CR to address this issue. The relevant sections in the CAT/CSW 3.0 spec (OGC 12-176r6) are: Table 19, Requirement-087, and the `MaxRecordsType` in the schema.

I believe the SWG is currently accepting informal change requests in addition to CRs submitted using the [official channel](http://www.opengeospatial.org/standards/cr).

**Comment by pvretano** [comment]
Removed as per pending CR from mhogeweg.
